---

- name: Update apt cache
  apt: update_cache=yes
  become: yes
  become_user: root

- name: Install basic packages
  apt: "pkg={{item}} state=installed"
  with_items:
    - vim
    - fish
    - tmux
    - htop
    - wget
    - iotop
  become: yes
  become_user: root

- include: vim.yml

#- include: tmux.yml

#- include: git.yml

- include: fish.yml

