---

- name: Update apt cache
  apt: update_cache=yes
  become: yes
  become_user: root

- name: Ensure .config/ is here and is owned by the user
  file:
    path: ~/.config
    mode: 0750
    state: directory
    owner: "{{shaka-server_username}}"
    group: "{{shaka-server_username}}"
  become: yes
  become_user: root


- name: Install basic packages
  apt: "pkg={{item}} state=installed"
  with_items:
    - vim
    - fish
    - tmux
    - htop
    - wget
    - iotop
  become: yes
  become_user: root

- include: vim.yml

#- include: tmux.yml

#- include: git.yml

- include: fish.yml

