---

- name: Clone shaka's vim-config repo
  git:
    repo: git://github.com/hugoShaka/vim-config.git
    dest: "{{shakaServer_home}}/.vim"

- name: Symlink vimrc
  file:
    src: "{{shakaServer_home}}/.vim/vimrc"
    dest: "{{shakaServer_home}}/.vimrc"
    state: link

